import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type AppLanguage = "en" | "ta" | "si";

type TranslationDict = Record<string, string>;

const translations: Record<AppLanguage, TranslationDict> = {
  en: {
    "language.label": "Language",
    "language.en": "English",
    "language.ta": "Tamil",
    "language.si": "Sinhala",
    "nav.home": "Home",
    "nav.marketplace": "Marketplace",
    "nav.prediction": "AI Prediction",
    "nav.dashboard": "Dashboard",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.getStarted": "Get Started",
    "nav.cart": "Cart",
    "layout.menu": "Dashboard Menu",
    "layout.farmer.title": "Farmer Dashboard",
    "layout.farmer.subtitle": "Manage products, orders, reports and profile",
    "layout.buyer.title": "Buyer Dashboard",
    "layout.buyer.subtitle": "Shop, manage orders, payments and support",
    "layout.admin.title": "Admin Dashboard",
    "layout.admin.subtitle": "Manage users, products, orders, payments and reports",
    "layout.switchAccount": "Switch account",
    "menu.overview": "Overview",
    "menu.profile": "Profile",
    "menu.products": "My Products",
    "menu.orders": "Orders",
    "menu.reports": "Sales Reports",
    "menu.complaints": "Complaints",
    "menu.marketplace": "Marketplace / Shop",
    "menu.payments": "Payments",
    "menu.users": "Users",
    "menu.farmerApproval": "Farmer Approval",
    "menu.productApproval": "Product Approval",
    "menu.aiPrediction": "AI Price Prediction",
    "home.badge": "Sri Lanka Smart Agri Market",
    "home.title1": "From Village Farm to",
    "home.title2": "Island-Wide Market",
    "home.subtitle": "Sri Lanka context AI system for vegetables and fruits. Farmers can predict prices, plan harvest timing, and sell directly with better margins.",
    "home.farmerFriendly": "Farmer Language Friendly",
    "home.farmerStart": "Farmer Start",
    "home.explore": "Explore Sri Lanka Market",
    "home.vegetableLane": "Vegetable Lane",
    "home.vegetableDesc": "Tomato, beans, leeks, pumpkin, and more from trusted farms with live availability.",
    "home.fruitLane": "Fruit Lane",
    "home.fruitDesc": "Banana, papaya, mango, pineapple and seasonal produce with AI pricing insights.",
    "home.featuresTitle": "Why This Works for Sri Lanka Farmers",
    "home.featuresSubtitle": "One platform for price prediction, selling, buying, and farm business planning",
    "home.howTitle": "How It Works",
    "home.howSubtitle": "Simple steps to get started",
    "home.ctaTitle": "Ready to Launch a Smart Sri Lankan Farm Business?",
    "home.ctaSubtitle": "Designed for local climate, local crops, and local trade behavior so farmers can earn more.",
    "home.startSelling": "Start Selling",
    "home.startBuying": "Start Buying",
    "home.footer": "Empowering Sri Lankan farmers and communities.",
    "login.welcome": "Welcome Back",
    "login.subtitle": "Sign in to your account to continue",
    "login.title": "Login",
    "login.desc": "Choose your account type and sign in",
    "login.buyer": "Buyer",
    "login.farmer": "Farmer",
    "login.admin": "Admin",
    "login.email": "Email",
    "login.password": "Password",
    "login.signingIn": "Signing in...",
    "login.signInAs": "Sign In as",
    "login.noAccount": "Don't have an account?",
    "login.registerHere": "Register here",
    "price.heroTitle": "AI Price Prediction",
    "price.heroSubtitle": "Select date and district to get weather-based price advice.",
    "price.formTitle": "Crop Details",
    "price.formDesc": "Enter date, district, and crop. Weather values will be filled automatically.",
    "price.category": "Category",
    "price.crop": "Crop",
    "price.district": "District",
    "price.date": "Date",
    "price.getWeather": "Get Weather",
    "price.loadingWeather": "Loading weather...",
    "price.temperature": "Temperature",
    "price.rainfall": "Rainfall",
    "price.humidity": "Humidity",
    "price.predict": "Predict Price",
    "price.predicting": "Predicting...",
    "price.clear": "Clear",
    "price.weatherSummary": "Weather Summary",
    "price.howTitle": "How It Works",
    "price.dataTitle": "Climate Inputs Used",
    "price.dataDesc": "Weather values are auto-filled and can still be adjusted manually.",
    "price.results": "Results",
    "price.currentPrice": "Current Price",
    "price.predictedPrice": "Predicted Price",
    "price.trend": "Price Trend",
    "price.change": "Change",
    "price.bestSell": "Best Selling Time",
  },
  ta: {
    "language.label": "மொழி",
    "language.en": "ஆங்கிலம்",
    "language.ta": "தமிழ்",
    "language.si": "சிங்களம்",
    "nav.home": "முகப்பு",
    "nav.marketplace": "சந்தை",
    "nav.prediction": "AI கணிப்பு",
    "nav.dashboard": "டாஷ்போர்டு",
    "nav.login": "உள்நுழை",
    "nav.logout": "வெளியேறு",
    "nav.getStarted": "தொடங்கு",
    "nav.cart": "கார்ட்",
    "layout.menu": "டாஷ்போர்டு பட்டியல்",
    "layout.farmer.title": "விவசாயி டாஷ்போர்டு",
    "layout.farmer.subtitle": "பொருட்கள், ஆர்டர்கள், அறிக்கைகள் மற்றும் சுயவிவரத்தை நிர்வகிக்கவும்",
    "layout.buyer.title": "வாங்குபவர் டாஷ்போர்டு",
    "layout.buyer.subtitle": "வாங்குதல், ஆர்டர்கள், கட்டணங்கள் மற்றும் உதவி",
    "layout.admin.title": "நிர்வாகி டாஷ்போர்டு",
    "layout.admin.subtitle": "பயனர்கள், பொருட்கள், ஆர்டர்கள், கட்டணங்கள் மற்றும் அறிக்கைகள்",
    "layout.switchAccount": "கணக்கை மாற்று",
    "menu.overview": "மேலோட்டம்",
    "menu.profile": "சுயவிவரம்",
    "menu.products": "என் பொருட்கள்",
    "menu.orders": "ஆர்டர்கள்",
    "menu.reports": "விற்பனை அறிக்கைகள்",
    "menu.complaints": "புகார்கள்",
    "menu.marketplace": "சந்தை / கடை",
    "menu.payments": "கட்டணங்கள்",
    "menu.users": "பயனர்கள்",
    "menu.farmerApproval": "விவசாயி ஒப்புதல்",
    "menu.productApproval": "பொருள் ஒப்புதல்",
    "menu.aiPrediction": "AI விலை கணிப்பு",
    "home.badge": "இலங்கை ஸ்மார்ட் வேளாண் சந்தை",
    "home.title1": "கிராமப்புற பண்ணையிலிருந்து",
    "home.title2": "நாட்டுமுழு சந்தைக்கு",
    "home.subtitle": "இலங்கைக்கான காய்கறி மற்றும் பழ AI அமைப்பு. விவசாயிகள் விலையை கணிக்கவும், அறுவடை நேரம் திட்டமிடவும், நேரடியாக விற்கவும் முடியும்.",
    "home.farmerFriendly": "விவசாயி மொழி நட்பு",
    "home.farmerStart": "விவசாயி தொடங்கு",
    "home.explore": "இலங்கை சந்தையை பாருங்கள்",
    "home.vegetableLane": "காய்கறி பகுதி",
    "home.vegetableDesc": "தக்காளி, பீன்ஸ், லீக்ஸ், பூசணி மற்றும் பல.",
    "home.fruitLane": "பழ பகுதி",
    "home.fruitDesc": "வாழை, பப்பாளி, மாம்பழம், அன்னாசி மற்றும் காலநிலை பழங்கள்.",
    "home.featuresTitle": "ஏன் இது இலங்கை விவசாயிகளுக்கு பொருந்தும்",
    "home.featuresSubtitle": "விலை கணிப்பு, விற்பனை, வாங்குதல் மற்றும் பண்ணை திட்டமிடல்",
    "home.howTitle": "இது எப்படி செயல்படுகிறது",
    "home.howSubtitle": "தொடங்க எளிய படிகள்",
    "home.ctaTitle": "ஸ்மார்ட் இலங்கை வேளாண் வணிகத்தை தொடங்க தயாரா?",
    "home.ctaSubtitle": "உள்ளூர் காலநிலை, பயிர்கள் மற்றும் வணிக பழக்கங்களுக்கு பொருந்தும் வகையில் வடிவமைக்கப்பட்டது.",
    "home.startSelling": "விற்பனை தொடங்கு",
    "home.startBuying": "வாங்க தொடங்கு",
    "home.footer": "இலங்கை விவசாயிகள் மற்றும் சமூகங்களை வலுப்படுத்துகிறது.",
    "login.welcome": "மீண்டும் வரவேற்கிறோம்",
    "login.subtitle": "தொடர உங்கள் கணக்கில் உள்நுழைக",
    "login.title": "உள்நுழைவு",
    "login.desc": "கணக்கு வகையை தேர்வு செய்து உள்நுழைக",
    "login.buyer": "வாங்குபவர்",
    "login.farmer": "விவசாயி",
    "login.admin": "நிர்வாகி",
    "login.email": "மின்னஞ்சல்",
    "login.password": "கடவுச்சொல்",
    "login.signingIn": "உள்நுழைகிறது...",
    "login.signInAs": "உள்நுழை",
    "login.noAccount": "கணக்கு இல்லையா?",
    "login.registerHere": "இங்கே பதிவு செய்க",
    "price.heroTitle": "AI விலை கணிப்பு",
    "price.heroSubtitle": "தேதி மற்றும் மாவட்டத்தை தேர்வு செய்து விலை ஆலோசனை பெறுங்கள்.",
    "price.formTitle": "பயிர் விவரம்",
    "price.formDesc": "தேதி, மாவட்டம், பயிர் கொடுக்கவும். வானிலை மதிப்புகள் தானாக நிரப்படும்.",
    "price.category": "வகை",
    "price.crop": "பயிர்",
    "price.district": "மாவட்டம்",
    "price.date": "தேதி",
    "price.getWeather": "வானிலை பெறு",
    "price.loadingWeather": "வானிலை ஏற்றுகிறது...",
    "price.temperature": "வெப்பநிலை",
    "price.rainfall": "மழைவீழ்ச்சி",
    "price.humidity": "ஈரப்பதம்",
    "price.predict": "விலை கணிக்க",
    "price.predicting": "கணிக்கிறது...",
    "price.clear": "அழி",
    "price.weatherSummary": "வானிலை சுருக்கம்",
    "price.howTitle": "இது எப்படி செயல்படும்",
    "price.dataTitle": "பயன்படும் காலநிலை தரவு",
    "price.dataDesc": "வானிலை மதிப்புகள் தானாக நிரப்படும். தேவையெனில் மாற்றலாம்.",
    "price.results": "முடிவு",
    "price.currentPrice": "தற்போதைய விலை",
    "price.predictedPrice": "கணிக்கப்பட்ட விலை",
    "price.trend": "விலை போக்கு",
    "price.change": "மாற்றம்",
    "price.bestSell": "சிறந்த விற்பனை நேரம்",
  },
  si: {
    "language.label": "භාෂාව",
    "language.en": "ඉංග්රීසි",
    "language.ta": "දෙමළ",
    "language.si": "සිංහල",
    "nav.home": "මුල් පිටුව",
    "nav.marketplace": "වෙළඳපොළ",
    "nav.prediction": "AI අනාවැකි",
    "nav.dashboard": "ඩෑෂ්බෝඩ්",
    "nav.login": "පිවිසෙන්න",
    "nav.logout": "ඉවත් වන්න",
    "nav.getStarted": "ආරම්භ කරන්න",
    "nav.cart": "කරත්තය",
    "layout.menu": "ඩෑෂ්බෝඩ් මෙනුව",
    "layout.farmer.title": "ගොවි ඩෑෂ්බෝඩ්",
    "layout.farmer.subtitle": "නිෂ්පාදන, ඇණවුම්, වාර්තා සහ පැතිකඩ කළමනාකරණය",
    "layout.buyer.title": "ගැනුම්කරු ඩෑෂ්බෝඩ්",
    "layout.buyer.subtitle": "මිලදී ගැනීම, ඇණවුම්, ගෙවීම් සහ සහාය",
    "layout.admin.title": "පරිපාලක ඩෑෂ්බෝඩ්",
    "layout.admin.subtitle": "පරිශීලකයන්, නිෂ්පාදන, ඇණවුම්, ගෙවීම් සහ වාර්තා කළමනාකරණය",
    "layout.switchAccount": "ගිණුම මාරු කරන්න",
    "menu.overview": "සාරාංශය",
    "menu.profile": "පැතිකඩ",
    "menu.products": "මගේ නිෂ්පාදන",
    "menu.orders": "ඇණවුම්",
    "menu.reports": "විකුණුම් වාර්තා",
    "menu.complaints": "පැමිණිලි",
    "menu.marketplace": "වෙළඳපොළ / සාප්පුව",
    "menu.payments": "ගෙවීම්",
    "menu.users": "පරිශීලකයන්",
    "menu.farmerApproval": "ගොවි අනුමැතිය",
    "menu.productApproval": "නිෂ්පාදන අනුමැතිය",
    "menu.aiPrediction": "AI මිල අනාවැකිය",
    "home.badge": "ශ්‍රී ලංකා ස්මාර්ට් කෘෂි වෙළඳපොළ",
    "home.title1": "ගමේ ගොවිපොළෙන්",
    "home.title2": "දිවයින පුරා වෙළඳපොළට",
    "home.subtitle": "එළවළු සහ පලතුරු සඳහා ශ්‍රී ලංකා සන්දර්භ AI පද්ධතියක්.",
    "home.farmerFriendly": "ගොවියාට හිතකාමී භාෂාව",
    "home.farmerStart": "ගොවියා ආරම්භ කරන්න",
    "home.explore": "ශ්‍රී ලංකා වෙළඳපොළ බලන්න",
    "home.vegetableLane": "එළවළු කොටස",
    "home.vegetableDesc": "තක්කාලි, බීන්ස්, ලීක්ස්, වට්ටක්කා සහ තවත් බොහෝ දේ.",
    "home.fruitLane": "පලතුරු කොටස",
    "home.fruitDesc": "කෙසෙල්, පැපොල්, අඹ, අන්නාසි සහ කාලීන පලතුරු.",
    "home.featuresTitle": "මෙය ශ්‍රී ලංකා ගොවීන්ට ගැළපෙන්නේ ඇයි",
    "home.featuresSubtitle": "මිල අනාවැකි, විකිණීම, මිලදී ගැනීම සහ ගොවි සැලසුම්",
    "home.howTitle": "මෙය ක්රියා කරන ආකාරය",
    "home.howSubtitle": "ආරම්භ කිරීමට පහසු පියවර",
    "home.ctaTitle": "ස්මාර්ට් ශ්‍රී ලාංකික ගොවි ව්‍යාපාරයක් ආරම්භ කිරීමට සූදානම්ද?",
    "home.ctaSubtitle": "දේශීය දේශගුණය, බෝග සහ වෙළඳ පුරුදු සඳහා නිර්මාණය කර ඇත.",
    "home.startSelling": "විකිණීම ආරම්භ කරන්න",
    "home.startBuying": "මිලදී ගැනීම ආරම්භ කරන්න",
    "home.footer": "ශ්‍රී ලංකා ගොවීන් සහ ප්‍රජාව සවිබල ගන්වයි.",
    "login.welcome": "නැවත සාදරයෙන් පිළිගනිමු",
    "login.subtitle": "ඉදිරියට යාමට ගිණුමට පිවිසෙන්න",
    "login.title": "පිවිසීම",
    "login.desc": "ගිණුම් වර්ගය තෝරා පිවිසෙන්න",
    "login.buyer": "ගැනුම්කරු",
    "login.farmer": "ගොවි",
    "login.admin": "පරිපාලක",
    "login.email": "විද්‍යුත් තැපෑල",
    "login.password": "මුරපදය",
    "login.signingIn": "පිවිසෙමින්...",
    "login.signInAs": "පිවිසෙන්න",
    "login.noAccount": "ගිණුමක් නැද්ද?",
    "login.registerHere": "මෙතැන ලියාපදිංචි වන්න",
    "price.heroTitle": "AI මිල අනාවැකිය",
    "price.heroSubtitle": "දිනය සහ දිස්ත්‍රික්කය තෝරා දේශගුණය පදනම් වූ මිල උපදෙස් ලබාගන්න.",
    "price.formTitle": "භෝග විස්තර",
    "price.formDesc": "දිනය, දිස්ත්‍රික්කය සහ භෝගය ඇතුළත් කරන්න. කාලගුණ අගයන් ස්වයංක්‍රීයව පුරවයි.",
    "price.category": "වර්ගය",
    "price.crop": "භෝගය",
    "price.district": "දිස්ත්‍රික්කය",
    "price.date": "දිනය",
    "price.getWeather": "කාලගුණය ගන්න",
    "price.loadingWeather": "කාලගුණය ලබාගනිමින්...",
    "price.temperature": "උෂ්ණත්වය",
    "price.rainfall": "වර්ෂාපතනය",
    "price.humidity": "ආර්ද්‍රතාව",
    "price.predict": "මිල අනාවැකි",
    "price.predicting": "අනාවැකි සකසමින්...",
    "price.clear": "මකන්න",
    "price.weatherSummary": "කාලගුණ සාරාංශය",
    "price.howTitle": "මෙය ක්රියා කරන ආකාරය",
    "price.dataTitle": "භාවිත වන දේශගුණ දත්ත",
    "price.dataDesc": "කාලගුණ අගයන් ස්වයංක්‍රීයව පුරවයි. අවශ්‍ය නම් වෙනස් කළ හැක.",
    "price.results": "ප්‍රතිඵල",
    "price.currentPrice": "වත්මන් මිල",
    "price.predictedPrice": "අනාවැකි මිල",
    "price.trend": "මිල ප්‍රවණතාව",
    "price.change": "වෙනස",
    "price.bestSell": "හොඳම විකිණීමේ වේලාව",
  },
};

type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  t: (key: string) => string;
};

const STORAGE_KEY = "app-language";

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<AppLanguage>(() => {
    const stored = localStorage.getItem(STORAGE_KEY) as AppLanguage | null;
    return stored ?? "en";
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => translations[language][key] ?? translations.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
